[package]
name = "cerf"
version = "0.1.0"
edition = "2024"

[dependencies]
dirs = "6.0.0"
glob = "0.3"
nom = "8.0.0"
rustyline = "17.0.2"

[target.'cfg(unix)'.dependencies]
nix = { version = "0.31.1", features = ["signal"] }
